// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT_blbrgUo_2HSX6lvemAHZkEUUeWldpM',
    appId: '1:996256225333:web:abf39fe544efe9fb6ef97c',
    messagingSenderId: '996256225333',
    projectId: 'lalo-2605',
    authDomain: 'lalo-2605.firebaseapp.com',
    storageBucket: 'lalo-2605.appspot.com',
    measurementId: 'G-66JHNB47LS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpGDxdAPrskjrgdvmKbIcx22ZGQHbvP2M',
    appId: '1:996256225333:android:4272519e77f553096ef97c',
    messagingSenderId: '996256225333',
    projectId: 'lalo-2605',
    storageBucket: 'lalo-2605.appspot.com',
  );
}
