# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Distribute a new version to Firebase"
  lane :distribute do
    sh("firebase deploy")
    sh("flutter build appbundle --release")
        # build_android_app is a built-in fastlane action.
        release = firebase_app_distribution(
            app: "1:996256225333:android:4272519e77f553096ef97c",
            testers: "kjell5317@gmail.com",
            release_notes: "Lots of amazing new features to test out!",
            android_artifact_type: "AAB",
            firebase_cli_path: "/usr/local/bin/firebase",
            android_artifact_path: "build/app/outputs/bundle/release/app-release.aab",
            firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
        )
  end

  lane :increment do
    sh('cd .. && git ci . -m "Build $(pubver bump build)"')
  end

  desc "Runs all the tests"
  lane :test do
    sh("flutter test")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    sh("firebase deploy")
    sh("flutter build appbundle --release")
    # upload_to_play_store
  end
end
