# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Distribute a new version to Firebase"
  lane :distribute do
    increment()
    sh("firebase deploy")
    # App Distribution can only process AABs when the Firebase project is
    # linked to a Google Play developer account; without one, distribute APKs.
    sh("flutter build apk --release")
        release = firebase_app_distribution(
            app: ENV["FIREBASE_APP_ID"],
            testers: "kjell5317@gmail.com",
            release_notes: "Lots of amazing new features to test out!",
            android_artifact_type: "APK",
            android_artifact_path: "build/app/outputs/flutter-apk/app-release.apk",
            service_credentials_file: ENV["GOOGLE_APPLICATION_CREDENTIALS"]
        )
  end

  desc "Bump the build number"
  lane :increment do
    sh("cd .. && cider bump build")
  end
end
