name: Distribute App

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.8"
          channel: "stable"
      - run: flutter pub global activate pubspec_version
      - run: bundle exec fastlane increment
      - uses: stefanzweifel/git-auto-commit-action@v4
